# -*- coding: utf-8 -*-
"""Task4_GPT_Text_Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WzKGzcvZoPYvyJTb8nMlh2nEeGLRc2Cd
"""

!pip install transformers
!pip install torch

from transformers import GPT2LMHeadModel, GPT2Tokenizer
import torch

# Load pre-trained model and tokenizer
model_name = "gpt2"  # or "gpt2-medium" for larger
tokenizer = GPT2Tokenizer.from_pretrained(model_name)
model = GPT2LMHeadModel.from_pretrained(model_name)
model.eval()

def generate_text(prompt, max_length=150):
    input_ids = tokenizer.encode(prompt, return_tensors='pt')
    with torch.no_grad():
        output = model.generate(
            input_ids,
            max_length=max_length,
            num_return_sequences=1,
            no_repeat_ngram_size=2,
            top_k=50,
            top_p=0.95,
            temperature=0.7
        )
    return tokenizer.decode(output[0], skip_special_tokens=True)

user_prompt = input("Enter a topic or a prompt: ")
generated_text = generate_text(user_prompt)
print("\nGenerated Text:\n")
print(generated_text)